"""User-maintained industry templates for Rivalens planning."""

from .directions import (
    INDUSTRY_DIRECTION_TEMPLATES,
    L0_COMMON_DIRECTIONS,
    L1_ARCHETYPE_DIRECTIONS,
    L2_REGULATED_DOMAIN_DIRECTIONS,
)

__all__ = [
    "INDUSTRY_DIRECTION_TEMPLATES",
    "L0_COMMON_DIRECTIONS",
    "L1_ARCHETYPE_DIRECTIONS",
    "L2_REGULATED_DOMAIN_DIRECTIONS",
]
