"""Deterministic industry direction templates.

Edit this file to control the default search directions shown by
IndustryDirectionSkill. The skill does not invent industry-specific directions.
"""

INDUSTRY_DIRECTION_TEMPLATES = [
    {
        "industry": "saas_collaboration",
        "display_name": "SaaS / 协作文档工具",
        "aliases": ["互联网", "saas", "software", "订阅", "协作", "效率", "云服务", "文档"],
        "known_competitors": ["notion", "slack", "zoom", "asana", "monday", "airtable", "飞书", "钉钉"],
        "default_directions": [
            {
                "direction_id": "features",
                "name": "核心功能对比",
                "reason": "协作文档类产品的基础分析维度",
                "required": True,
            },
            {
                "direction_id": "pricing",
                "name": "定价模式对比",
                "reason": "企业采购和产品定位的重要依据",
                "required": True,
            },
            {
                "direction_id": "security",
                "name": "企业安全能力",
                "reason": "SaaS 企业版竞争中的关键因素",
                "required": True,
            },
            {
                "direction_id": "integrations",
                "name": "集成生态",
                "reason": "影响团队工作流迁移和长期留存",
                "required": False,
            },
            {
                "direction_id": "user_reviews",
                "name": "用户评价与痛点",
                "reason": "用于判断真实使用体验",
                "required": True,
            },
        ],
    },
    {
        "industry_id": "ecommerce_retail",
        "name": "电商/零售",
        "aliases": ["电商", "零售", "retail", "marketplace", "d2c", "新零售", "商城"],
        "known_competitors": ["amazon", "shopify", "淘宝", "京东", "拼多多", "抖音电商"],
        "directions": [
            {"direction_id": "pricing", "name": "价格策略", "reason": "价格带和补贴直接影响转化与定位"},
            {"direction_id": "logistics", "name": "物流履约", "reason": "履约体验是电商竞争的核心变量"},
            {"direction_id": "assortment", "name": "品类与供给", "reason": "品类覆盖决定用户选择空间"},
            {"direction_id": "promotions", "name": "促销机制", "reason": "促销影响获客、复购和平台心智"},
            {"direction_id": "user_reviews", "name": "用户评价与投诉", "reason": "用于判断真实购物体验"},
        ],
    },
    {
        "industry_id": "financial_services",
        "name": "金融/经济服务",
        "aliases": ["金融", "经济服务", "fintech", "支付", "银行", "理财", "保险", "风控"],
        "known_competitors": ["stripe", "paypal", "wise", "adyen", "支付宝", "微信支付", "陆金所"],
        "directions": [
            {"direction_id": "fees", "name": "费率结构", "reason": "费率决定商户成本和盈利空间"},
            {"direction_id": "compliance", "name": "合规能力", "reason": "金融服务必须满足准入和审查要求"},
            {"direction_id": "risk_control", "name": "风控能力", "reason": "风控影响坏账、欺诈和交易安全"},
            {"direction_id": "security", "name": "安全能力", "reason": "资金和账户安全是用户信任基础"},
            {"direction_id": "regulatory_disclosure", "name": "监管披露", "reason": "披露信息可验证牌照、风险和合规边界"},
        ],
    },
    {
        "industry_id": "edtech",
        "name": "教育科技",
        "aliases": ["教育", "edtech", "在线课程", "学习", "培训", "教培", "lms"],
        "known_competitors": ["coursera", "duolingo", "作业帮", "猿辅导", "学而思", "kahoot"],
        "directions": [
            {"direction_id": "curriculum", "name": "课程体系", "reason": "课程结构决定学习路径和目标人群"},
            {"direction_id": "learning_outcomes", "name": "学习效果", "reason": "效果证明影响付费和续费"},
            {"direction_id": "teacher_resources", "name": "师资资源", "reason": "师资和教研影响内容质量"},
            {"direction_id": "pricing", "name": "定价模式", "reason": "价格影响获客门槛和商业化"},
            {"direction_id": "user_reviews", "name": "用户评价与口碑", "reason": "用于判断真实学习体验"},
        ],
    },
    {
        "industry_id": "healthcare",
        "name": "医疗健康",
        "aliases": ["医疗", "医疔", "健康", "healthcare", "medical", "clinic", "patient", "医药"],
        "known_competitors": ["teladoc", "zocdoc", "平安好医生", "丁香园", "微医", "epic"],
        "directions": [
            {"direction_id": "qualification", "name": "资质与认证", "reason": "医疗健康服务需要可验证资质"},
            {"direction_id": "privacy", "name": "隐私保护", "reason": "患者和健康数据属于高敏感信息"},
            {"direction_id": "security", "name": "安全能力", "reason": "平台安全影响服务可信度"},
            {"direction_id": "service_scope", "name": "服务范围", "reason": "服务覆盖决定适用场景和用户边界"},
            {"direction_id": "doctor_resources", "name": "医生资源", "reason": "医生供给直接影响服务能力和体验"},
        ],
    },
    {
        "industry_id": "travel_mobility",
        "name": "旅游出行",
        "aliases": ["旅游", "出行", "travel", "mobility", "酒店", "机票", "打车", "航旅"],
        "known_competitors": ["booking", "airbnb", "携程", "飞猪", "滴滴", "uber", "lyft"],
        "directions": [
            {"direction_id": "pricing", "name": "价格与费用", "reason": "价格透明度影响预订决策"},
            {"direction_id": "supply_coverage", "name": "供给覆盖", "reason": "供给覆盖决定可选范围"},
            {"direction_id": "booking_experience", "name": "预订体验", "reason": "链路体验影响转化率"},
            {"direction_id": "cancellation_policy", "name": "取消政策", "reason": "取消和退款影响用户信任"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价反映真实履约体验"},
        ],
    },
    {
        "industry_id": "local_services",
        "name": "本地生活",
        "aliases": ["本地生活", "到店", "外卖", "团购", "local services", "餐饮到店", "生活服务"],
        "known_competitors": ["美团", "大众点评", "饿了么", "doordash", "ubereats", "yelp"],
        "directions": [
            {"direction_id": "pricing", "name": "价格与补贴", "reason": "价格和补贴影响获客与复购"},
            {"direction_id": "merchant_coverage", "name": "商户覆盖", "reason": "供给密度决定平台竞争力"},
            {"direction_id": "fulfillment", "name": "配送/履约", "reason": "履约体验影响用户满意度"},
            {"direction_id": "membership", "name": "优惠会员", "reason": "会员权益影响长期留存"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价可揭示服务稳定性"},
        ],
    },
    {
        "industry_id": "gaming_entertainment",
        "name": "游戏娱乐",
        "aliases": ["游戏", "娱乐", "game", "gaming", "直播", "视频", "音乐", "内容平台"],
        "known_competitors": ["steam", "roblox", "twitch", "bilibili", "网易游戏", "腾讯游戏", "spotify"],
        "directions": [
            {"direction_id": "content_ip", "name": "内容/IP", "reason": "内容供给决定平台吸引力"},
            {"direction_id": "experience", "name": "玩法/体验", "reason": "体验差异影响留存"},
            {"direction_id": "monetization", "name": "付费模式", "reason": "商业化设计影响收入结构"},
            {"direction_id": "community", "name": "社区生态", "reason": "社区影响传播和活跃度"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价可反映真实满意度"},
        ],
    },
    {
        "industry_id": "automotive_new_energy",
        "name": "汽车/新能源",
        "aliases": ["汽车", "新能源", "ev", "电动车", "充电", "自动驾驶", "车企"],
        "known_competitors": ["tesla", "比亚迪", "蔚来", "理想", "小鹏", "极氪"],
        "directions": [
            {"direction_id": "vehicle_specs", "name": "车型参数", "reason": "参数是车型横向比较的基础"},
            {"direction_id": "pricing", "name": "价格与权益", "reason": "价格和权益影响购买决策"},
            {"direction_id": "charging_network", "name": "补能网络", "reason": "补能能力影响使用体验"},
            {"direction_id": "smart_features", "name": "智能化能力", "reason": "智能化是新能源竞争重点"},
            {"direction_id": "after_sales", "name": "售后服务", "reason": "售后影响长期口碑"},
        ],
    },
    {
        "industry_id": "enterprise_services",
        "name": "企业服务",
        "aliases": ["企业服务", "b2b", "enterprise", "crm", "erp", "hr", "财税", "法务"],
        "known_competitors": ["salesforce", "sap", "oracle", "servicenow", "用友", "金蝶", "纷享销客"],
        "directions": [
            {"direction_id": "features", "name": "核心功能", "reason": "功能覆盖决定业务适配度"},
            {"direction_id": "pricing", "name": "定价模式", "reason": "企业采购高度关注总成本"},
            {"direction_id": "implementation", "name": "实施交付", "reason": "实施能力影响上线风险"},
            {"direction_id": "integrations", "name": "系统集成", "reason": "企业系统需要打通上下游流程"},
            {"direction_id": "security_compliance", "name": "安全合规", "reason": "企业服务必须满足治理要求"},
        ],
    },
    {
        "industry_id": "consumer_food",
        "name": "消费品/餐饮",
        "aliases": ["消费品", "餐饮", "fmcg", "食品", "饮料", "连锁餐饮", "咖啡", "茶饮"],
        "known_competitors": ["starbucks", "mcdonalds", "瑞幸", "喜茶", "元气森林", "农夫山泉"],
        "directions": [
            {"direction_id": "pricing", "name": "价格带", "reason": "价格带决定消费人群"},
            {"direction_id": "sku_menu", "name": "SKU/菜单", "reason": "产品组合体现品牌策略"},
            {"direction_id": "channels", "name": "渠道门店", "reason": "渠道影响触达和规模"},
            {"direction_id": "promotions", "name": "促销活动", "reason": "促销影响短期增长"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价反映真实消费体验"},
        ],
    },
    {
        "industry_id": "real_estate_property",
        "name": "房地产/物业",
        "aliases": ["房地产", "物业", "地产", "租房", "长租", "写字楼", "real estate", "property"],
        "known_competitors": ["链家", "贝壳", "万科", "碧桂园服务", "绿城服务", "wework"],
        "directions": [
            {"direction_id": "assets", "name": "项目/房源", "reason": "资产供给决定业务基础"},
            {"direction_id": "pricing_fees", "name": "价格/收费", "reason": "费用透明度影响信任"},
            {"direction_id": "regional_coverage", "name": "区域覆盖", "reason": "区域覆盖决定规模和密度"},
            {"direction_id": "service_quality", "name": "服务质量", "reason": "服务体验影响续约和口碑"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价可揭示运营问题"},
        ],
    },
    {
        "industry_id": "logistics_supply_chain",
        "name": "物流供应链",
        "aliases": ["物流", "供应链", "快递", "仓储", "货运", "supply chain", "logistics"],
        "known_competitors": ["顺丰", "京东物流", "菜鸟", "dhl", "fedex", "满帮"],
        "directions": [
            {"direction_id": "pricing", "name": "价格", "reason": "价格决定客户成本"},
            {"direction_id": "delivery_speed", "name": "时效", "reason": "时效是物流服务核心指标"},
            {"direction_id": "network_coverage", "name": "网络覆盖", "reason": "网络覆盖影响履约能力"},
            {"direction_id": "exception_handling", "name": "异常处理", "reason": "异常处理决定服务稳定性"},
            {"direction_id": "digital_capability", "name": "数字化能力", "reason": "数字化能力影响可视化和协同效率"},
        ],
    },
    {
        "industry_id": "ai_tools_llm",
        "name": "AI工具/大模型",
        "aliases": ["ai", "大模型", "llm", "agent", "copilot", "生成式", "智能体", "模型"],
        "known_competitors": ["openai", "anthropic", "claude", "chatgpt", "gemini", "通义", "文心", "kimi"],
        "directions": [
            {"direction_id": "model_capability", "name": "模型能力", "reason": "模型能力决定场景边界"},
            {"direction_id": "pricing", "name": "价格", "reason": "价格影响开发者和企业采用"},
            {"direction_id": "security", "name": "安全", "reason": "企业使用 AI 工具需要安全承诺"},
            {"direction_id": "developer_ecosystem", "name": "开发者生态", "reason": "生态影响集成和扩展能力"},
            {"direction_id": "user_reviews", "name": "用户评价", "reason": "评价可反映真实使用体验"},
        ],
    },
]
