"""Deterministic industry direction templates.

Edit this file to control the default search directions shown by
IndustryDirectionSkill. The skill does not invent industry-specific directions.
Each direction should describe a public, source-backed research focus.
"""

INDUSTRY_DIRECTION_TEMPLATES = [
    {
        "industry_id": "saas_collaboration",
        "name": "SaaS / 协作文档工具",
        "aliases": [
            "互联网",
            "saas",
            "software",
            "订阅",
            "协作",
            "效率",
            "云服务",
            "文档",
            "知识库",
            "project management",
        ],
        "known_competitors": [
            "notion",
            "slack",
            "zoom",
            "asana",
            "monday",
            "airtable",
            "飞书",
            "钉钉",
        ],
        "directions": [
            {
                "direction_id": "pricing_packaging",
                "name": "定价与套餐分层",
                "reason": "免费版、团队版、企业版、AI 加购和用量限制直接影响 SaaS 采购决策。",
                "source_hints": ["pricing_page", "official_site", "review"],
                "required": True,
            },
            {
                "direction_id": "collaboration_workflows",
                "name": "协作工作流能力",
                "reason": "多人编辑、评论、权限、审批、任务流和知识库协作是协作文档产品的核心差异。",
                "source_hints": ["official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "integrations_ecosystem",
                "name": "集成与生态",
                "reason": "第三方集成、API、模板和插件生态决定团队工作流迁移成本和长期粘性。",
                "source_hints": ["marketplace", "docs", "official_site"],
                "required": True,
            },
            {
                "direction_id": "ai_assistance",
                "name": "AI 写作与知识助手",
                "reason": "AI 搜索、总结、写作和自动化已成为协作文档工具的重要差异化能力。",
                "source_hints": ["official_site", "pricing_page", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "security_admin_controls",
                "name": "安全、权限与管理",
                "reason": "SSO、审计、数据保留、权限模型和合规说明是企业客户采购的关键门槛。",
                "source_hints": ["trust_center", "docs", "official_site", "pricing_page"],
                "required": True,
            },
            {
                "direction_id": "reliability_status_sla",
                "name": "可靠性、状态页与 SLA",
                "reason": "状态页、SLA、事故记录和服务可用性直接影响团队日常协作风险。",
                "source_hints": ["status_page", "trust_center", "docs", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "templates_use_cases",
                "name": "模板与场景覆盖",
                "reason": "模板能展示产品覆盖的真实工作场景，如项目管理、CRM、会议纪要和知识库。",
                "source_hints": ["official_site", "marketplace", "social"],
                "required": False,
            },
            {
                "direction_id": "user_sentiment_reviews",
                "name": "用户评价与痛点",
                "reason": "公开评论能暴露性能、学习成本、迁移难度和协作体验等官网外问题。",
                "source_hints": ["review", "social", "marketplace"],
                "required": False,
            },
            {
                "direction_id": "mobile_offline_experience",
                "name": "移动端体验与离线能力",
                "reason": "收集各竞品移动端功能完整度、离线编辑支持情况，以及移动端与桌面端的功能差距，重点关注实际用户在移动端的协作体验评价。",
                "source_hints": ["review", "official_site", "social"],
                "required": False,
            },
            {
                "direction_id": "data_portability_migration",
                "name": "数据迁移与导出自由度",
                "reason": "收集各竞品支持的导出格式（Markdown、CSV、PDF、API 导出）、官方数据迁移工具、数据归属条款，以及用户从该产品迁出或从竞品迁入的实际难度评价。",
                "source_hints": ["docs", "official_site", "review"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "ecommerce_retail",
        "name": "电商 / 零售",
        "aliases": [
            "电商",
            "零售",
            "retail",
            "marketplace",
            "d2c",
            "新零售",
            "商城",
            "卖家",
            "商家",
        ],
        "known_competitors": [
            "amazon",
            "shopify",
            "walmart",
            "淘宝",
            "京东",
            "拼多多",
            "抖音电商",
        ],
        "directions": [
            {
                "direction_id": "pricing_fees",
                "name": "平台收费与商家成本",
                "reason": "抽佣、履约费、订阅费和广告费决定商家利润和平台变现能力。",
                "source_hints": ["pricing_page", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "fulfillment_returns",
                "name": "履约、配送与退货",
                "reason": "到货速度、配送承诺、退货门槛和退货成本直接影响用户体验和复购。",
                "source_hints": ["official_site", "docs", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "assortment_catalog",
                "name": "商品供给与目录质量",
                "reason": "SKU 覆盖、类目深度、品牌和第三方卖家结构决定平台差异化。",
                "source_hints": ["marketplace", "official_site", "review", "other"],
                "required": True,
            },
            {
                "direction_id": "seller_tools",
                "name": "卖家运营工具",
                "reason": "商品管理、库存、价格、广告、报表、API 和客服工具影响商家迁移成本。",
                "source_hints": ["official_site", "docs", "marketplace", "job_posting"],
                "required": True,
            },
            {
                "direction_id": "trust_reviews",
                "name": "信任、评价与假货治理",
                "reason": "商品评价、卖家评分、正品保障和投诉处理是交易平台的信任基础设施。",
                "source_hints": ["review", "official_site", "docs", "news", "social"],
                "required": True,
            },
            {
                "direction_id": "promotion_loyalty",
                "name": "促销、会员与流量分发",
                "reason": "优惠券、会员权益、推荐位、广告产品和排序机制影响商家获客效率。",
                "source_hints": ["official_site", "pricing_page", "marketplace", "news"],
                "required": True,
            },
            {
                "direction_id": "ads_search_ranking",
                "name": "广告、搜索排序与流量分发",
                "reason": "站内广告、搜索排序、推荐位和活动资源位决定商家获客成本与平台商业化效率。",
                "source_hints": ["official_site", "docs", "marketplace", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "live_content_commerce",
                "name": "直播与内容电商能力",
                "reason": "收集各竞品直播带货功能、短视频挂链、达人/KOL 招募政策、内容种草到成交的转化路径，以及直播 GMV 占比和内容电商战略布局。",
                "source_hints": ["official_site", "news", "social", "marketplace"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "financial_services",
        "name": "金融 / 支付 / Fintech",
        "aliases": [
            "金融",
            "经济服务",
            "fintech",
            "支付",
            "银行",
            "理财",
            "保险",
            "风控",
            "payment",
        ],
        "known_competitors": [
            "stripe",
            "paypal",
            "wise",
            "adyen",
            "square",
            "支付宝",
            "微信支付",
            "陆金所",
        ],
        "directions": [
            {
                "direction_id": "licenses_compliance",
                "name": "牌照与监管合规",
                "reason": "金融和支付业务依赖牌照、注册、监管范围和合规披露，决定能否合法展业。",
                "source_hints": ["regulator_database", "public_registry", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "payment_security",
                "name": "支付与数据安全",
                "reason": "支付链路涉及账户、卡号、身份与交易数据，安全披露是高信任行业核心指标。",
                "source_hints": ["standards_body", "trust_center", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "fraud_risk_controls",
                "name": "反欺诈与风险控制",
                "reason": "诈骗、盗刷、账户接管和异常交易处置能力影响用户损失与监管风险。",
                "source_hints": ["official_site", "docs", "news", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "pricing_fee_transparency",
                "name": "定价与费用透明度",
                "reason": "手续费、汇率、提现费、逾期费和订阅费决定用户真实成本。",
                "source_hints": ["pricing_page", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "consumer_complaints",
                "name": "投诉与纠纷处理",
                "reason": "投诉库、应用商店、社媒和新闻能公开反映服务缺陷与企业响应质量。",
                "source_hints": ["complaint_database", "review", "social", "news"],
                "required": True,
            },
            {
                "direction_id": "ecosystem_integrations",
                "name": "银行与生态集成",
                "reason": "支持的银行、卡组织、钱包、会计系统、商户平台和 API 体现落地能力。",
                "source_hints": ["docs", "marketplace", "official_site"],
                "required": True,
            },
            {
                "direction_id": "disclosure_transparency",
                "name": "信息披露与用户保护",
                "reason": "风险提示、隐私政策、资金托管、保险保障和状态页能验证关键风险披露。",
                "source_hints": ["financial_filing", "trust_center", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "merchant_developer_api",
                "name": "商户与开发者 API 接入体验",
                "reason": "收集各竞品的 API 文档质量、SDK 语言覆盖、沙箱测试环境、Webhook 可靠性，以及开发者社区对接入难度的真实评价。Stripe 的崛起核心就是 API 体验优于 PayPal，这是 B2B 支付竞品最重要的差异化维度之一。",
                "source_hints": ["docs", "official_site", "review", "social"],
                "required": False,
            },
            {
                "direction_id": "payment_success_settlement",
                "name": "支付成功率与结算时效",
                "reason": "收集各竞品的交易成功率、拒付率（chargeback rate）、结算到账周期（T+0/T+1/T+2）和异常交易处理时效，这是投资人和大商户选择支付平台的核心性能指标。",
                "source_hints": ["status_page", "official_site", "docs", "review", "news"],
                "required": False,
            },
            {
                "direction_id": "aml_kyc_sanctions",
                "name": "AML/KYC 与制裁筛查",
                "reason": "反洗钱、客户身份识别、制裁名单筛查和商户审核是支付与金融平台的准入型风险控制。",
                "source_hints": ["regulator_database", "standards_body", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "fund_safeguarding",
                "name": "客户资金隔离与保障",
                "reason": "资金托管、隔离账户、赔付机制和破产风险披露决定用户和商户资金安全。",
                "source_hints": ["regulator_database", "financial_filing", "official_site", "docs", "news"],
                "required": True,
            },
        ],
    },
    {
        "industry_id": "edtech",
        "name": "教育科技 / 在线学习",
        "aliases": [
            "教育",
            "edtech",
            "在线课程",
            "学习",
            "培训",
            "教培",
            "lms",
            "课程",
        ],
        "known_competitors": [
            "coursera",
            "duolingo",
            "udemy",
            "kahoot",
            "作业帮",
            "猿辅导",
            "学而思",
        ],
        "directions": [
            {
                "direction_id": "course_catalog_depth",
                "name": "课程目录与内容深度",
                "reason": "课程、证书、学位、技能路径和垂直领域覆盖是在线学习平台的核心供给。",
                "source_hints": ["official_site", "docs", "marketplace"],
                "required": True,
            },
            {
                "direction_id": "credential_value",
                "name": "证书与职业价值",
                "reason": "证书背书、就业导向和可分享凭证影响用户付费意愿与企业采购价值。",
                "source_hints": ["official_site", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "learning_experience",
                "name": "学习体验与完成机制",
                "reason": "课程结构、项目作业、测验、节奏、互动和移动端体验影响留存与完课。",
                "source_hints": ["official_site", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "pricing_access_model",
                "name": "价格与访问模式",
                "reason": "免费试听、单课购买、订阅、企业版和证书收费决定获客门槛。",
                "source_hints": ["pricing_page", "official_site", "review"],
                "required": True,
            },
            {
                "direction_id": "skills_assessment_analytics",
                "name": "技能评估与学习分析",
                "reason": "企业培训会关注技能测评、学习进度、团队报表和 ROI 证明。",
                "source_hints": ["official_site", "docs", "case_study", "other"],
                "required": True,
            },
            {
                "direction_id": "privacy_accessibility_compliance",
                "name": "学生隐私、无障碍与教育合规",
                "reason": "学生数据保护、儿童隐私、无障碍访问和学校采购合规是教育科技产品进入机构场景的前提。",
                "source_hints": ["regulator_database", "standards_body", "trust_center", "official_site", "docs"],
                "required": True,
            },
            {
                "direction_id": "partner_instructor_network",
                "name": "内容伙伴与讲师生态",
                "reason": "大学、企业、讲师和机构合作决定内容权威性、更新速度和差异化。",
                "source_hints": ["official_site", "news", "job_posting"],
                "required": False,
            },
            {
                "direction_id": "learner_outcomes_reviews",
                "name": "学员结果与评价",
                "reason": "课程评分、评论、就业结果和学习收益报告能补足官网宣传。",
                "source_hints": ["case_study", "review", "official_site", "social", "analyst_report"],
                "required": True,
            },
            {
                "direction_id": "ai_personalization_learning",
                "name": "AI 个性化与自适应学习",
                "reason": "收集各竞品的 AI 辅助功能：自适应学习路径、AI 出题与批改、对话式 AI 辅导（如 Khanmigo、Duolingo Max）、AI 反馈质量，以及 AI 功能是否额外收费。这是 2024 年后 edtech 竞品分析的核心差异化维度。",
                "source_hints": ["official_site", "docs", "news", "review"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "healthcare",
        "name": "医疗健康",
        "aliases": [
            "医疗",
            "医药",
            "健康",
            "healthcare",
            "medical",
            "clinic",
            "patient",
            "医生",
            "医院",
        ],
        "known_competitors": [
            "teladoc",
            "zocdoc",
            "epic",
            "平安好医生",
            "丁香园",
            "微医",
        ],
        "directions": [
            {
                "direction_id": "regulatory_clearance",
                "name": "医疗资质与监管准入",
                "reason": "医疗器械、数字疗法、检测服务和远程医疗需要明确监管路径或执业资质。",
                "source_hints": ["regulator_database", "public_registry", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "clinical_evidence",
                "name": "临床证据与有效性",
                "reason": "高信任医疗产品必须证明疗效、准确性或临床价值。",
                "source_hints": ["docs", "case_study", "official_site", "news", "analyst_report"],
                "required": True,
            },
            {
                "direction_id": "privacy_phi_security",
                "name": "隐私与健康数据安全",
                "reason": "健康数据、访问控制、加密、审计和泄露披露是医疗竞品分析的核心风险维度。",
                "source_hints": ["trust_center", "standards_body", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "patient_safety_quality",
                "name": "患者安全与质量指标",
                "reason": "不良事件、召回、服务质量和误诊漏诊风险直接影响信任与采购决策。",
                "source_hints": ["incident_database", "regulator_database", "official_site", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "provider_network_access",
                "name": "医生/机构网络与可及性",
                "reason": "服务覆盖、合作医院、医生资质、预约等待时间和保险覆盖决定实际履约能力。",
                "source_hints": ["public_registry", "official_site", "marketplace", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "pricing_insurance",
                "name": "价格、保险与支付方式",
                "reason": "自费价格、保险报销、订阅方案和费用透明度影响转化和投诉风险。",
                "source_hints": ["pricing_page", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "care_operations",
                "name": "诊疗流程与售后支持",
                "reason": "处方、复诊、检验、用药提醒、客服和紧急处理决定服务完整度。",
                "source_hints": ["official_site", "docs", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "pharmaceutical_supply_chain",
                "name": "药品供应链与医药电商整合",
                "reason": "收集各竞品在线处方药销售资质、药品配送能力（冷链/次日达）、处方流转合规性、自营药店 vs 第三方药店模式，以及药品业务在总营收中的比重。京东健康药品销售约占总营收 70%，是纯问诊平台难以复制的护城河。",
                "source_hints": ["regulator_database", "official_site", "docs", "news", "marketplace"],
                "required": False,
            },
            {
                "direction_id": "interoperability_ehr_fhir",
                "name": "EHR/FHIR 互操作与数据交换",
                "reason": "EHR 集成、FHIR/API、处方/检验系统连接和健康数据可携带性决定医疗产品能否嵌入真实诊疗流程。",
                "source_hints": ["standards_body", "docs", "official_site", "case_study", "news"],
                "required": True,
            },
        ],
    },
    {
        "industry_id": "travel_mobility",
        "name": "旅游出行",
        "aliases": [
            "旅游",
            "出行",
            "travel",
            "mobility",
            "酒店",
            "机票",
            "打车",
            "航旅",
            "民宿",
        ],
        "known_competitors": [
            "booking",
            "airbnb",
            "expedia",
            "携程",
            "飞猪",
            "滴滴",
            "uber",
            "lyft",
        ],
        "directions": [
            {
                "direction_id": "inventory_coverage",
                "name": "供给覆盖与库存类型",
                "reason": "酒店、机票、民宿、租车、活动和打车供给决定平台可比价能力与交易上限。",
                "source_hints": ["marketplace", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "pricing_transparency",
                "name": "价格、税费与总价透明",
                "reason": "税费、服务费、清洁费、动态价格和渠道价差影响用户信任。",
                "source_hints": ["pricing_page", "official_site", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "cancellation_refunds",
                "name": "取消、改签与退款政策",
                "reason": "旅游订单高客单且强计划性，取消和退款体验显著影响复购。",
                "source_hints": ["docs", "official_site", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "partner_connectivity",
                "name": "供应商连接与渠道能力",
                "reason": "酒店、航司、房东和车队的 API、库存同步、支付结算决定供给稳定性。",
                "source_hints": ["docs", "official_site", "job_posting", "other"],
                "required": True,
            },
            {
                "direction_id": "trust_safety_reviews",
                "name": "身份验证、安全与评价",
                "reason": "住宿、出行和体验服务有线下风险，身份验证、互评和保障计划是关键。",
                "source_hints": ["trust_center", "official_site", "docs", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "disruption_support_insurance",
                "name": "行程中断、客服保障与保险",
                "reason": "航班改签、酒店拒单、司机取消、事故保险和退款 SLA 决定旅游出行平台的真实履约兜底能力。",
                "source_hints": ["official_site", "docs", "complaint_database", "review", "news"],
                "required": False,
            },
            {
                "direction_id": "loyalty_membership",
                "name": "会员、积分与权益",
                "reason": "会员等级、积分、返现和价格保护影响复购与跨品类迁移。",
                "source_hints": ["official_site", "pricing_page", "news", "review"],
                "required": False,
            },
            {
                "direction_id": "search_packaging",
                "name": "搜索筛选与组合打包",
                "reason": "搜索排序、地图、价格日历、机酒打包和行程推荐影响转化效率。",
                "source_hints": ["official_site", "marketplace", "review", "other"],
                "required": True,
            },
        ],
    },
    {
        "industry_id": "local_services",
        "name": "本地生活 / 到店到家",
        "aliases": [
            "本地生活",
            "到店",
            "外卖",
            "团购",
            "local services",
            "餐饮到店",
            "生活服务",
            "配送",
        ],
        "known_competitors": [
            "美团",
            "大众点评",
            "饿了么",
            "doordash",
            "ubereats",
            "yelp",
        ],
        "directions": [
            {
                "direction_id": "merchant_commission",
                "name": "商家佣金与套餐",
                "reason": "外卖和到店平台常以佣金、配送方式和曝光权益绑定商家套餐。",
                "source_hints": ["pricing_page", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "delivery_eta_accuracy",
                "name": "配送时效与 ETA 准确率",
                "reason": "收集各竞品的承诺送达时间、实际配送时效达标率、ETA 算法准确性、高峰期与恶劣天气下的运力稳定性，以及差评中超时配送的频率。研究表明 ETA 准确性是外卖复购率的第一预测变量。",
                "source_hints": ["official_site", "review", "social", "news"],
                "required": True,
            },
            {
                "direction_id": "delivery_fulfillment",
                "name": "配送履约与服务范围",
                "reason": "配送费、配送半径、峰值供给和骑手可用性直接影响平台密度与体验。",
                "source_hints": ["official_site", "docs", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "merchant_supply",
                "name": "商家供给密度与品类",
                "reason": "区域覆盖、热门商户、品类深度和高评分供给构成本地服务壁垒。",
                "source_hints": ["marketplace", "official_site", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "consumer_fees_subscription",
                "name": "用户费用与会员权益",
                "reason": "服务费、小单费、配送费和会员免配送费影响实际成交价。",
                "source_hints": ["pricing_page", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "quality_refunds",
                "name": "质量控制、退款与投诉",
                "reason": "错漏单、超时、服务质量和退款机制是履约平台体验差异的高频来源。",
                "source_hints": ["docs", "review", "social", "news"],
                "required": True,
            },
            {
                "direction_id": "discovery_reviews_ranking",
                "name": "本地发现、评价榜单与搜索排序",
                "reason": "评价可信度、榜单、搜索排序和商家广告决定用户发现效率与商家获客质量。",
                "source_hints": ["marketplace", "review", "official_site", "docs", "social"],
                "required": True,
            },
            {
                "direction_id": "merchant_qualification_safety",
                "name": "商户资质、食品安全与信息准确性",
                "reason": "商户资质、食品安全、菜单库存、价格与实际服务一致性是本地生活平台的准入型治理要求。",
                "source_hints": ["public_registry", "regulator_database", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "merchant_marketing_tools",
                "name": "商家营销与运营工具",
                "reason": "商户后台、活动报名、广告、报表和 POS/API 集成决定商家运营效率。",
                "source_hints": ["official_site", "docs", "marketplace", "job_posting"],
                "required": False,
            },
            {
                "direction_id": "worker_supply",
                "name": "骑手/服务人员供给机制",
                "reason": "招募、激励、排班、收入争议和劳动政策影响履约稳定性。",
                "source_hints": ["job_posting", "news", "social", "other"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "gaming_entertainment",
        "name": "游戏 / 娱乐 / 内容平台",
        "aliases": [
            "游戏",
            "娱乐",
            "game",
            "gaming",
            "直播",
            "视频",
            "音乐",
            "内容平台",
            "社区",
        ],
        "known_competitors": [
            "steam",
            "roblox",
            "twitch",
            "bilibili",
            "网易游戏",
            "腾讯游戏",
            "spotify",
        ],
        "directions": [
            {
                "direction_id": "content_catalog_ip",
                "name": "内容矩阵与 IP",
                "reason": "游戏、影视、音乐和短剧的核心竞争力来自内容类型、IP、题材和更新储备。",
                "source_hints": ["official_site", "marketplace", "news", "social"],
                "required": True,
            },
            {
                "direction_id": "monetization_model",
                "name": "变现模式",
                "reason": "买断、订阅、广告、内购、通行证、打赏和会员分层决定收入结构。",
                "source_hints": ["pricing_page", "official_site", "marketplace", "docs"],
                "required": True,
            },
            {
                "direction_id": "platform_distribution",
                "name": "平台与发行渠道",
                "reason": "应用商店、主机、PC 平台、视频平台和内容渠道影响触达与转化。",
                "source_hints": ["marketplace", "official_site", "news", "other"],
                "required": True,
            },
            {
                "direction_id": "liveops_events",
                "name": "运营活动与留存机制",
                "reason": "版本更新、赛季、活动、榜单、任务和内容排期影响长期活跃。",
                "source_hints": ["official_site", "social", "news", "marketplace"],
                "required": True,
            },
            {
                "direction_id": "community_ugc",
                "name": "社区与 UGC 生态",
                "reason": "社区、二创、MOD、评论区和创作者投稿影响传播与生命周期。",
                "source_hints": ["social", "review", "marketplace", "official_site"],
                "required": True,
            },
            {
                "direction_id": "safety_moderation_compliance",
                "name": "内容安全、审核与平台合规",
                "reason": "未成年人保护、内容审核、版权、封禁政策、内购概率披露和社区规范是游戏娱乐产品的准入风险。",
                "source_hints": ["regulator_database", "official_site", "docs", "marketplace", "news"],
                "required": True,
            },
            {
                "direction_id": "reviews_performance",
                "name": "评分、评论与性能体验",
                "reason": "公开评论能验证玩法、内容质量、稳定性、付费争议和设备问题。",
                "source_hints": ["review", "marketplace", "social"],
                "required": True,
            },
            {
                "direction_id": "creator_partner_signal",
                "name": "创作者与合作信号",
                "reason": "主播、KOL、版权合作、联名和招聘可反映增长策略和内容供给方向。",
                "source_hints": ["social", "news", "job_posting", "official_site"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "automotive_new_energy",
        "name": "汽车 / 新能源",
        "aliases": [
            "汽车",
            "新能源",
            "ev",
            "电动车",
            "充电",
            "自动驾驶",
            "车企",
            "智驾",
        ],
        "known_competitors": [
            "tesla",
            "比亚迪",
            "蔚来",
            "理想",
            "小鹏",
            "极氪",
        ],
        "directions": [
            {
                "direction_id": "safety_recalls",
                "name": "安全评级与召回",
                "reason": "安全评级、召回频率、缺陷类型和整改能力是车辆信任基础。",
                "source_hints": ["regulator_database", "incident_database", "official_site", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "battery_range_efficiency",
                "name": "电池、续航与能耗",
                "reason": "电池容量、续航、能耗、热管理、衰减承诺和实际体验决定 EV 核心竞争力。",
                "source_hints": ["official_site", "docs", "review", "other"],
                "required": True,
            },
            {
                "direction_id": "charging_ecosystem",
                "name": "补能网络与兼容性",
                "reason": "充电网络覆盖、功率、接口兼容、漫游合作和可用率影响使用体验。",
                "source_hints": ["official_site", "docs", "marketplace", "review", "other"],
                "required": True,
            },
            {
                "direction_id": "warranty_service",
                "name": "质保与售后服务能力",
                "reason": "电池质保、整车质保、维修网点、OTA 处理和备件供应影响长期拥有成本。",
                "source_hints": ["official_site", "docs", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "adas_software_safety",
                "name": "智驾与软件安全",
                "reason": "ADAS、自动驾驶、OTA 和车联网安全会影响监管关注和差异化卖点。",
                "source_hints": ["incident_database", "standards_body", "official_site", "docs", "news", "review"],
                "required": True,
            },
            {
                "direction_id": "ota_cybersecurity",
                "name": "OTA、车联网与网络安全",
                "reason": "OTA 更新机制、车联网安全、漏洞披露和软件召回影响智能汽车的长期安全与监管风险。",
                "source_hints": ["standards_body", "incident_database", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "compliance_emissions",
                "name": "法规、排放与认证",
                "reason": "排放、能耗、碰撞、软件召回和市场准入决定产品能否稳定销售。",
                "source_hints": ["official_site", "docs", "news", "other"],
                "required": True,
            },
            {
                "direction_id": "ownership_cost",
                "name": "总拥有成本",
                "reason": "价格、补贴、保险、保养、电耗、残值和维修成本决定消费者真实购买决策。",
                "source_hints": ["pricing_page", "official_site", "review", "marketplace"],
                "required": True,
            },
            {
                "direction_id": "smart_cockpit_system",
                "name": "智能座舱与车机系统",
                "reason": "收集各竞品的车机操作系统（自研 vs 安卓定制）、语音助手能力、车载 App 生态（第三方 App 数量）、屏幕配置、与手机生态互联方案（CarPlay/华为 HiCar/小米互联），以及用户对车机流畅度和交互体验的真实评价。智能座舱是 2024 年国内新能源竞争的第二战场。",
                "source_hints": ["official_site", "review", "social", "news"],
                "required": False,
            },
            {
                "direction_id": "sales_volume_market_share",
                "name": "月度销量与市占率趋势",
                "reason": "收集各竞品的月度/季度交付量、细分市场市占率变化趋势、爆款车型销量占比，以及订单量 vs 交付量比率（反映产能与交付能力）。数据来源包括乘联会、中汽协等公开统计。",
                "source_hints": ["news", "official_site", "other"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "enterprise_services",
        "name": "企业服务 / B2B 软件",
        "aliases": [
            "企业服务",
            "b2b",
            "enterprise",
            "crm",
            "erp",
            "hr",
            "财税",
            "法务",
            "采购",
        ],
        "known_competitors": [
            "salesforce",
            "sap",
            "oracle",
            "servicenow",
            "用友",
            "金蝶",
            "纷享销客",
        ],
        "directions": [
            {
                "direction_id": "target_segments",
                "name": "目标客户与行业场景",
                "reason": "B2B 软件通常按 SMB、中型企业、大客户或垂直行业定位，影响销售和功能优先级。",
                "source_hints": ["official_site", "other", "review"],
                "required": True,
            },
            {
                "direction_id": "pricing_contracting",
                "name": "定价、合同与采购方式",
                "reason": "seat、usage、enterprise quote、私有报价和云市场采购决定商业化路径。",
                "source_hints": ["pricing_page", "marketplace", "official_site", "review"],
                "required": True,
            },
            {
                "direction_id": "enterprise_features",
                "name": "企业级功能",
                "reason": "SSO、RBAC、审计、数据治理、工作流和报表决定能否进入企业采购清单。",
                "source_hints": ["official_site", "docs", "pricing_page"],
                "required": True,
            },
            {
                "direction_id": "implementation_onboarding",
                "name": "实施与上手成本",
                "reason": "迁移、配置、培训和客户成功支持决定销售周期和上线风险。",
                "source_hints": ["official_site", "docs", "review", "job_posting"],
                "required": True,
            },
            {
                "direction_id": "integrations_platform",
                "name": "平台集成与 API",
                "reason": "与 CRM、ERP、数据仓库、身份系统和云市场集成决定替换成本和扩展价值。",
                "source_hints": ["docs", "marketplace", "official_site"],
                "required": True,
            },
            {
                "direction_id": "proof_and_trust",
                "name": "客户案例与可信度",
                "reason": "客户案例、合规认证、行业评测和公开排名能支撑企业采购信任。",
                "source_hints": ["case_study", "trust_center", "analyst_report", "official_site", "review"],
                "required": True,
            },
            {
                "direction_id": "sla_support_reliability",
                "name": "SLA、支持等级与服务可靠性",
                "reason": "SLA、状态页、客户支持等级、事故响应和运维透明度是企业采购委员会评估供应商风险的核心依据。",
                "source_hints": ["status_page", "trust_center", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "buyer_reviews_objections",
                "name": "买家评价与反对点",
                "reason": "公开评论能提炼采购顾虑、续费风险和竞品替换理由。",
                "source_hints": ["review", "marketplace", "social"],
                "required": False,
            },
            {
                "direction_id": "vendor_lock_in_risk",
                "name": "供应商锁定风险与数据可迁移性",
                "reason": "收集各竞品的数据导出格式与完整性、API 开放程度、合同中的数据归属条款、官方迁移工具支持情况，以及用户评价中反映的更换成本和被锁定程度。B2B 采购法务团队必查项。",
                "source_hints": ["docs", "official_site", "review", "other"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "consumer_food",
        "name": "消费品 / 餐饮",
        "aliases": [
            "消费品",
            "餐饮",
            "fmcg",
            "食品",
            "饮料",
            "连锁餐饮",
            "咖啡",
            "茶饮",
            "零食",
        ],
        "known_competitors": [
            "starbucks",
            "mcdonalds",
            "瑞幸",
            "喜茶",
            "元气森林",
            "农夫山泉",
        ],
        "directions": [
            {
                "direction_id": "product_portfolio_sku",
                "name": "产品组合与 SKU",
                "reason": "品类、口味、规格、套餐和新品节奏是定位与差异化分析基础。",
                "source_hints": ["official_site", "marketplace", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "pricing_packaging",
                "name": "定价与包装规格",
                "reason": "价格带、容量、套餐、捆绑和促销价决定消费人群和性价比感知。",
                "source_hints": ["pricing_page", "official_site", "marketplace", "review"],
                "required": True,
            },
            {
                "direction_id": "food_safety_labeling_claims",
                "name": "食品安全、标签与健康声明",
                "reason": "食品安全、营养标签、过敏原、配料表和健康功效声明是食品饮料与餐饮品牌的高优先级合规基础。",
                "source_hints": ["regulator_database", "standards_body", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "channel_distribution",
                "name": "渠道与销售场景",
                "reason": "直营、电商、外卖、商超、便利店、经销渠道和区域覆盖决定触达能力。",
                "source_hints": ["official_site", "marketplace", "social", "news", "other"],
                "required": True,
            },
            {
                "direction_id": "promotions_membership",
                "name": "促销、会员与活动",
                "reason": "满减、积分、联名、节日活动和会员权益影响拉新、复购与品牌热度。",
                "source_hints": ["official_site", "pricing_page", "social", "news"],
                "required": True,
            },
            {
                "direction_id": "brand_social_content",
                "name": "品牌内容与社媒表达",
                "reason": "社媒内容能反映品牌人设、目标客群、卖点叙事和营销节奏。",
                "source_hints": ["social", "official_site", "news"],
                "required": False,
            },
            {
                "direction_id": "reputation_quality",
                "name": "用户口碑与质量反馈",
                "reason": "评论能暴露口味、品质、物流、门店服务、包装和性价比等真实痛点。",
                "source_hints": ["review", "marketplace", "social"],
                "required": True,
            },
            {
                "direction_id": "expansion_supply_signal",
                "name": "扩张与供应链信号",
                "reason": "招聘、新闻和门店信息可反映新品、产能、区域扩张和渠道重点。",
                "source_hints": ["job_posting", "news", "official_site", "other"],
                "required": False,
            },
            {
                "direction_id": "unit_economics",
                "name": "单店经济模型",
                "reason": "收集各竞品的单店平均营收（AUV）、坪效、客单价、翻台率/翻杯率、投资回收周期，以及直营 vs 加盟单店盈利对比。这是判断连锁餐饮/消费品商业模式可持续性的核心财务指标，是投资人必看的第一优先维度。",
                "source_hints": ["news", "official_site", "other", "review"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "real_estate_property",
        "name": "房地产 / 物业 / 租赁",
        "aliases": [
            "房地产",
            "物业",
            "地产",
            "租房",
            "长租",
            "写字楼",
            "real estate",
            "property",
            "房源",
        ],
        "known_competitors": [
            "链家",
            "贝壳",
            "万科",
            "碧桂园服务",
            "绿城服务",
            "wework",
            "zillow",
        ],
        "directions": [
            {
                "direction_id": "listing_inventory",
                "name": "房源供给与 listing 质量",
                "reason": "房源数量、真实性、图片、户型、可租日期和设施信息决定搜索效率与可信度。",
                "source_hints": ["marketplace", "official_site", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "total_cost_transparency",
                "name": "租金、押金与费用透明",
                "reason": "租金、押金、申请费、宠物费、物业费和月度总价是租赁决策核心。",
                "source_hints": ["pricing_page", "official_site", "complaint_database", "review", "news"],
                "required": True,
            },
            {
                "direction_id": "fair_housing_advertising_compliance",
                "name": "公平住房、广告与筛选合规",
                "reason": "公平住房、反歧视、广告投放、租客筛选和费用披露合规决定房产平台的高信任底线。",
                "source_hints": ["regulator_database", "public_registry", "official_site", "docs", "news"],
                "required": True,
            },
            {
                "direction_id": "lead_tours_conversion",
                "name": "线索、看房与转化流程",
                "reason": "预约看房、在线咨询、VR 看房和线索分发影响房东与经纪人获客效率。",
                "source_hints": ["official_site", "marketplace", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "tenant_screening",
                "name": "租客申请与筛选",
                "reason": "背景调查、信用报告、收入验证和申请费关系到房东风控与租客体验。",
                "source_hints": ["regulator_database", "official_site", "pricing_page", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "lease_payments_maintenance",
                "name": "签约、收租与维修闭环",
                "reason": "在线签约、租金支付、自动提醒和维修工单体现物业运营价值。",
                "source_hints": ["official_site", "pricing_page", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "trust_scam_safety",
                "name": "反欺诈、评价与安全保障",
                "reason": "虚假房源、押金诈骗、身份验证和评价机制是房产平台高风险议题。",
                "source_hints": ["complaint_database", "official_site", "review", "social", "news"],
                "required": True,
            },
            {
                "direction_id": "landlord_pricing_packages",
                "name": "房东/物业方收费与套餐",
                "reason": "发布费、曝光升级、线索套餐和按单元计费影响供给侧采用意愿。",
                "source_hints": ["pricing_page", "official_site", "docs", "marketplace"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "logistics_supply_chain",
        "name": "物流 / 供应链",
        "aliases": [
            "物流",
            "供应链",
            "快递",
            "仓储",
            "货运",
            "supply chain",
            "logistics",
            "履约",
        ],
        "known_competitors": [
            "顺丰",
            "京东物流",
            "菜鸟",
            "dhl",
            "fedex",
            "满帮",
        ],
        "directions": [
            {
                "direction_id": "operating_authority",
                "name": "运营资质与授权",
                "reason": "承运人、经纪人、货代和跨境业务必须验证经营资质、保险和海关授权。",
                "source_hints": ["public_registry", "regulator_database", "official_site", "docs"],
                "required": True,
            },
            {
                "direction_id": "safety_compliance",
                "name": "运输安全与合规记录",
                "reason": "安全评级、检查、事故和停运记录能公开反映承运风险和履约可靠性。",
                "source_hints": ["incident_database", "regulator_database", "official_site", "news"],
                "required": True,
            },
            {
                "direction_id": "service_coverage",
                "name": "服务网络与覆盖范围",
                "reason": "仓网、车队、航线、港口和国家/地区覆盖决定能否满足履约场景。",
                "source_hints": ["official_site", "docs", "marketplace"],
                "required": True,
            },
            {
                "direction_id": "delivery_performance",
                "name": "履约时效与服务承诺",
                "reason": "SLA、准点承诺、追踪能力和异常处理流程决定客户体验。",
                "source_hints": ["official_site", "docs", "review", "social"],
                "required": True,
            },
            {
                "direction_id": "supply_chain_security",
                "name": "供应链安全与风控",
                "reason": "货物防盗、身份核验、双重经纪防范、封签和仓储安保是高信任物流关键项。",
                "source_hints": ["official_site", "docs", "news", "other"],
                "required": True,
            },
            {
                "direction_id": "pricing_contracts",
                "name": "报价与计费透明度",
                "reason": "运价结构、燃油附加费、仓储费、偏远费和赔付条款影响采购比较。",
                "source_hints": ["pricing_page", "official_site", "docs", "review"],
                "required": True,
            },
            {
                "direction_id": "technology_visibility",
                "name": "追踪与系统集成",
                "reason": "API、TMS/WMS/ERP 集成、可视化和电子回单体现企业客户适配度。",
                "source_hints": ["docs", "marketplace", "official_site"],
                "required": True,
            },
            {
                "direction_id": "digitalization_open_platform",
                "name": "数字化平台与开放 API 能力",
                "reason": "收集各竞品的开放平台能力：API 对接文档完整度、WMS/TMS/ERP 集成成熟度、IoT 应用（智能仓/自动分拣/无人配送）、大客户专属数字化方案，以及开发者对接入难度的评价。顺丰丰桥、京东青龙等开放平台是当前物流竞争最核心的技术壁垒。",
                "source_hints": ["docs", "official_site", "news", "job_posting"],
                "required": False,
            },
        ],
    },
    {
        "industry_id": "ai_tools_llm",
        "name": "AI 工具 / 大模型",
        "aliases": [
            "ai",
            "人工智能",
            "大模型",
            "llm",
            "agent",
            "copilot",
            "生成式",
            "智能体",
            "模型",
        ],
        "known_competitors": [
            "openai",
            "anthropic",
            "claude",
            "chatgpt",
            "gemini",
            "通义",
            "文心",
            "kimi",
        ],
        "directions": [
            {
                "direction_id": "model_capabilities",
                "name": "模型能力与适用任务",
                "reason": "AI 竞品必须比较文本、代码、图像、语音、多模态、工具调用和长上下文能力边界。",
                "source_hints": ["docs", "official_site", "news"],
                "required": True,
            },
            {
                "direction_id": "pricing_usage_limits",
                "name": "价格、计费与额度",
                "reason": "API token 价格、订阅价、速率限制、上下文窗口和工具调用费用影响采用成本。",
                "source_hints": ["pricing_page", "docs", "official_site"],
                "required": True,
            },
            {
                "direction_id": "benchmarks_evaluations",
                "name": "评测与基准表现",
                "reason": "benchmark、系统卡、模型卡和公开评测能形成可引用证据。",
                "source_hints": ["benchmark", "docs", "official_site", "news", "analyst_report"],
                "required": True,
            },
            {
                "direction_id": "developer_experience",
                "name": "开发者体验与 API",
                "reason": "SDK、文档、函数调用、批处理、RAG、fine-tuning 和控制台能力决定开发者采用。",
                "source_hints": ["docs", "official_site", "social"],
                "required": True,
            },
            {
                "direction_id": "safety_compliance",
                "name": "安全、合规与治理",
                "reason": "企业采用 AI 时关注数据使用、隐私、内容安全、模型卡、红队和合规声明。",
                "source_hints": ["trust_center", "standards_body", "docs", "official_site", "news"],
                "required": True,
            },
            {
                "direction_id": "data_usage_training_policy",
                "name": "数据使用、训练策略与企业边界",
                "reason": "输入数据是否用于训练、数据保留周期、企业隔离、区域处理和隐私承诺直接决定 AI 工具能否被企业采用。",
                "source_hints": ["trust_center", "docs", "official_site", "news"],
                "required": True,
            },
            {
                "direction_id": "deployment_options",
                "name": "部署与访问方式",
                "reason": "云 API、私有化、开源权重、区域可用性和企业托管影响行业适配与采购路径。",
                "source_hints": ["official_site", "docs", "marketplace", "news"],
                "required": True,
            },
            {
                "direction_id": "ecosystem_adoption",
                "name": "生态采用与社区热度",
                "reason": "插件、应用商店、开源社区、开发者讨论和集成数量能反映真实扩散速度。",
                "source_hints": ["marketplace", "social", "docs", "review"],
                "required": False,
            },
            {
                "direction_id": "context_window_long_context",
                "name": "上下文窗口与长文处理质量",
                "reason": "收集各竞品支持的最大上下文长度（128K/200K/1M token）、长文档信息检索准确率（needle-in-a-haystack 测试表现）、超长上下文时的响应质量衰减情况。这是开发者选型时最常问的第一个技术问题。",
                "source_hints": ["benchmark", "docs", "official_site", "news"],
                "required": False,
            },
            {
                "direction_id": "inference_speed_latency",
                "name": "推理速度与输出延迟",
                "reason": "收集各竞品的首 token 时间（TTFT）、输出速度（tokens/s）、流式输出稳定性，以及高并发场景下的延迟表现。这是面向 C 端产品和实时 API 应用的核心性能指标，直接影响产品用户体验。",
                "source_hints": ["benchmark", "status_page", "docs", "official_site", "review"],
                "required": False,
            },
            {
                "direction_id": "multimodal_capabilities",
                "name": "多模态能力覆盖",
                "reason": "收集各竞品支持的模态类型（图像理解、语音转文字、视频理解、图像生成）、各模态的实际质量与限制，以及多模态功能的定价方式和 API 可用性。GPT-4o 时代多模态已是标配竞争维度。",
                "source_hints": ["docs", "official_site", "news", "review"],
                "required": False,
            },
            {
                "direction_id": "finetuning_rag_customization",
                "name": "微调与 RAG 定制化能力",
                "reason": "收集各竞品是否开放 Fine-tuning API、支持的训练数据格式与微调成本、Embedding API 质量、知识库/RAG 集成方案，以及企业客户将通用模型定制为专属模型的难度和效果评价。",
                "source_hints": ["docs", "official_site", "news", "review"],
                "required": False,
            },
        ],
    },
]
