"""Structured competitor knowledge schema."""

from .competitive import (
    AgentEvent,
    AgentMessage,
    AgentMessagePayload,
    AgentMessageType,
    AnalysisMessagePayload,
    AnalysisClaim,
    AnalysisClaimPayload,
    Competitor,
    CompetitorAnalysisState,
    CompetitorPayload,
    EvidenceMessagePayload,
    EvidenceItem,
    PlanMessagePayload,
    ProductFact,
    ProductFactPayload,
    PublishMessagePayload,
    QualityFinding,
    QualityFindingPayload,
    ReportMessagePayload,
    ResearchArtifact,
    ReviewMessagePayload,
    RevisionMessagePayload,
    SchemaMessagePayload,
)

__all__ = [
    "AgentEvent",
    "AgentMessage",
    "AgentMessagePayload",
    "AgentMessageType",
    "AnalysisMessagePayload",
    "AnalysisClaim",
    "AnalysisClaimPayload",
    "Competitor",
    "CompetitorAnalysisState",
    "CompetitorPayload",
    "EvidenceMessagePayload",
    "EvidenceItem",
    "PlanMessagePayload",
    "ProductFact",
    "ProductFactPayload",
    "PublishMessagePayload",
    "QualityFinding",
    "QualityFindingPayload",
    "ReportMessagePayload",
    "ResearchArtifact",
    "ReviewMessagePayload",
    "RevisionMessagePayload",
    "SchemaMessagePayload",
]
